### ISSUE TITLE
Remove jrIntroduction references

### ISSUE THREAD

**Issue by csgillespie** [jr-packages/jrIntroBio#3]
A quick search and replace should be fine.

This is why travis is failing https://travis-ci.org/jr-packages/jrIntroBio

**Comment by rmnppt** [comment]
ok but can I assume that users will have the `jrIntroduction` package? they will need it for example to get the function `GetNumericVector` which I did not copy.

**Comment by rmnppt** [comment]
I added `jr-packages/jrIntroduction to the remotes and now build is passing on travis. is that ok?
